[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
  " prefix
  nnoremap [Denite] <NOP>
  nmap <Space>d [Denite]

  " keymap
  nnoremap <silent> [Denite]f :<C-u>Denite file_rec<CR>
  nnoremap <silent> [Denite]o :<C-u>Denite -mode=normal outline<CR>
  nnoremap <silent> [Denite]g :<C-u>Denite -auto-highlight -mode=normal grep<CR>
  nnoremap <silent> [Denite]* :<C-u>DeniteCursorWord -auto-highlight -mode=normal grep<CR>
  nnoremap <silent> [Denite]h :<C-u>Denite help<CR>
  nnoremap <silent> [Denite]b :<C-u>Denite buffer<CR>
  nnoremap <silent> [Denite]FT :<C-u>Denite filetype<CR>
  nnoremap <silent> [Denite]<C-r> :<C-u>Denite command_history<CR>
'''
hook_source = '''
  " Change default prompt
  call denite#custom#option('default', 'prompt', '>')

  " Change mappings.
  call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
  call denite#custom#map('normal', '<esc>', '<denite:quit>', 'noremap')

  call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')

  call denite#custom#map('insert', '<C-t>', '<denite:do_action:tabopen>', 'noremap')
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = 'zsh'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
if = 'executable("javac")'
on_ft = 'java'
hook_source = '''
  autocmd MyAutoCmd FileType java setlocal omnifunc=javacomplete#Complete
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = 'neosnippet-snippets'
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
  imap <C-k>     <Plug>(neosnippet_jump_or_expand)
  smap <C-k>     <Plug>(neosnippet_jump_or_expand)
  xmap <C-k>     <Plug>(neosnippet_expand_target)

  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#expand_word_boundary = 1

  "let g:neosnippet#snippets_directory = 'path/to/snippets'
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'
hook_add = '''
  nnoremap <Space>sh :<C-u>NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
on_source = 'nerdtree'

[[plugins]]
repo = 'majutsushi/tagbar'
if = 'executable("ctags")'
on_cmd = 'TagbarToggle'
hook_add = '''
  nnoremap <Space>sl :<C-u>TagbarToggle<CR>
  let g:tagbar_autoshowtag = 1
'''

