[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  let g:solarized_termtrans=1
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme solarized
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

