[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
  " prefix
  nnoremap [Denite] <NOP>
  nmap <Space>d [Denite]

  " keymap
  nnoremap <silent> [Denite]f :<C-u>Denite buffer `finddir('.git', ';') != '' ? 'file/rec/git' : 'file/rec'`<CR>
  nnoremap <silent> [Denite]if :<C-u>Denite file/rec/gitignore<CR>
  nnoremap <silent> [Denite]af :<C-u>Denite file/rec/all<CR>
  nnoremap <silent> [Denite]o :<C-u>Denite outline -auto-highlight -mode=normal<CR>
  nnoremap <silent> [Denite]/ :<C-u>Denite grep -no-empty -mode=normal<CR>
  nnoremap <silent> [Denite]* :<C-u>DeniteCursorWord grep -no-empty -mode=normal<CR>
  nnoremap <silent> [Denite]t :<C-u>Denite tag<CR>
  nnoremap <silent> [Denite]<C-]> :<C-u>DeniteCursorWord tag -mode=normal<CR>

  nnoremap <silent> [Denite]r :<C-u>Denite -resume<CR>
  nnoremap <silent> [Denite]n :<C-u>Denite -resume -cursor-pos=+1 -immediately<CR>
  nnoremap <silent> [Denite]p :<C-u>Denite -resume -cursor-pos=-1 -immediately<CR>

  nnoremap <silent> [Denite]b :<C-u>Denite buffer -buffer-name=buf<CR>
  nnoremap <silent> [Denite]h :<C-u>Denite help -buffer-name=help<CR>
  nnoremap <silent> [Denite]<C-r> :<C-u>Denite command_history -buffer-name=history<CR>
  nnoremap <silent> [Denite]ein :<C-u>Denite dein_log -mode=normal<CR>

  nnoremap <silent> [Denite]cd :<C-u>DeniteProjectDir directory_rec -buffer-name=cd -default-action=cd<CR>

  nnoremap <silent> <Space>/ :<C-u>Denite line -auto-highlight -auto-resize -buffer-name=line<CR>
  nnoremap <silent> <Space>* :<C-u>DeniteCursorWord line -auto-highlight -auto-resize -buffer-name=line -mode=normal<CR>

  nnoremap <silent> FT :<C-u>Denite filetype -buffer-name=ft<CR>
  nnoremap <silent> [Denite]cs :<C-u>Denite colorscheme -buffer-name=cs<CR>

  nnoremap <silent> T :<C-u>Denite menu:toggle -buffer-name=toggle<CR>
'''
hook_source = 'source ~/.config/nvim/rc/denite.rc.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
on_ft = ['rust', 'go', 'python']
hook_add = '''
  let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ 'go': ['golsp'],
    \ 'python': ['pyls'],
    \ }
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
if = 'executable("javac")'
on_ft = 'java'
hook_source = '''
  autocmd MyAutoCmd FileType java setlocal omnifunc=javacomplete#Complete
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
  imap <C-k>     <Plug>(neosnippet_jump_or_expand)
  smap <C-k>     <Plug>(neosnippet_jump_or_expand)
  xmap <C-k>     <Plug>(neosnippet_expand_target)

  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#expand_word_boundary = 1

  "let g:neosnippet#snippets_directory = 'path/to/snippets'
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
  " for ALE
  let g:go_fmt_autosave = 0

  " highlight
  let g:go_highlight_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_function_calls = 1
  "let g:go_highlight_extra_types = 1
  "let g:go_highlight_operators = 1
  "let g:go_highlight_build_constraints = 1

  let g:go_auto_sameids = 1
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'

[[plugins]]
repo = 'majutsushi/tagbar'
if = 'executable("ctags")'
on_cmd = 'TagbarToggle'
hook_add = '''
  let g:tagbar_autoshowtag = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_event = 'InsertEnter'
hook_add = '''
  let g:table_mode_corner = '|'
'''
