[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
  " prefix
  nnoremap [Denite] <NOP>
  nmap <Space>d [Denite]

  " keymap
  nnoremap <silent> [Denite]f :<C-u>Denite `finddir('.git', ';') != '' ? 'file_rec/git' : 'file_rec'`<CR>
  nnoremap <silent> [Denite]if :<C-u>Denite file_rec/gitignore<CR>
  nnoremap <silent> [Denite]af :<C-u>Denite file_rec/all<CR>
  nnoremap <silent> [Denite]o :<C-u>Denite -auto-highlight -mode=normal outline<CR>
  nnoremap <silent> [Denite]/ :<C-u>Denite -no-empty -mode=normal grep<CR>
  nnoremap <silent> [Denite]* :<C-u>DeniteCursorWord -no-empty -mode=normal grep<CR>
  nnoremap <silent> [Denite]t :<C-u>Denite tag<CR>
  nnoremap <silent> [Denite]<C-]> :<C-u>DeniteCursorWord -mode=normal tag<CR>
  nnoremap <silent> [Denite]r :<C-u>Denite -resume<CR>

  nnoremap <silent> [Denite]b :<C-u>Denite -buffer-name=buf buffer<CR>
  nnoremap <silent> [Denite]h :<C-u>Denite -buffer-name=help help<CR>
  nnoremap <silent> [Denite]FT :<C-u>Denite -buffer-name=ft filetype<CR>
  nnoremap <silent> [Denite]<C-r> :<C-u>Denite -buffer-name=history command_history<CR>

  nnoremap <silent> / :<C-u>Denite -auto-highlight -auto-resize -buffer-name=line line<CR>
  nnoremap <silent> * :<C-u>DeniteCursorWord -auto-highlight -auto-resize -buffer-name=line -mode=normal line<CR>
'''
hook_source = '''
  " Change default prompt
  call denite#custom#option('default', 'prompt', '>')
  call denite#custom#option('help', 'prompt', 'help?')
  call denite#custom#option('ft', 'prompt', 'set ft =')
  call denite#custom#option('history', 'prompt', ':')
  call denite#custom#option('line', 'prompt', '/')

  " alias
  call denite#custom#alias('source', 'file_rec/git', 'file_rec')
  call denite#custom#var('file_rec/git', 'command',
        \ ['git', 'ls-files', '-co', '--exclude-standard'])

  call denite#custom#alias('source', 'file_rec/gitignore', 'file_rec')
  call denite#custom#var('file_rec/gitignore', 'command',
        \ ['git', 'ls-files', '-co', '--exclude-standard', '-i'])

  call denite#custom#alias('source', 'file_rec/all', 'file_rec')

  " file_rec
  if executable('ag')
    call denite#custom#var('file_rec', 'command',
          \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  endif

  " grep source
  if executable('rg')
    call denite#custom#var('grep', 'command', ['rg'])
    call denite#custom#var('grep', 'default_opts',
          \ ['--vimgrep', '--no-heading'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
    call denite#custom#var('grep', 'separator', ['--'])
    call denite#custom#var('grep', 'final_opts', [])
  endif

  " Change mappings.
  call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
  call denite#custom#map('normal', '<esc>', '<denite:quit>', 'noremap')

  call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')

  call denite#custom#map('insert', '<C-t>', '<denite:do_action:tabopen>', 'noremap')
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
if = 'executable("javac")'
on_ft = 'java'
hook_source = '''
  autocmd MyAutoCmd FileType java setlocal omnifunc=javacomplete#Complete
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = 'neosnippet-snippets'
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
  imap <C-k>     <Plug>(neosnippet_jump_or_expand)
  smap <C-k>     <Plug>(neosnippet_jump_or_expand)
  xmap <C-k>     <Plug>(neosnippet_expand_target)

  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#expand_word_boundary = 1

  "let g:neosnippet#snippets_directory = 'path/to/snippets'
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'
hook_add = '''
  nnoremap <silent> <Space>tr :<C-u>NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'majutsushi/tagbar'
if = 'executable("ctags")'
on_cmd = 'TagbarToggle'
hook_add = '''
  nnoremap <silent> <Space>tag :<C-u>TagbarToggle<CR>
  let g:tagbar_autoshowtag = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'

