[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  let g:solarized_termtrans=1
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme solarized
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = 'vim-airline/vim-airline_themes'
hook_add = '''
  let g:airline_solarized_bg='dark'

  let g:airline#extensions#tabline#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'zchee/deoplete-zsh'

[[plugins]]
repo = 'zplug/vim-zplug'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_fileTypeExclude = ['', 'help', 'nerdtree']
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
  nmap <Space>* <Plug>(quickhl-manual-this)
  nmap <Space>nohl <Plug>(quickhl-manual-reset)
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  " Map movement through errors without wrapping.
  nmap <silent> <C-k> <Plug>(ale_previous)
  nmap <silent> <C-j> <Plug>(ale_next)
'''

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
if = 'executable("ctags") || executable("gtags")'
hook_add = '''
  let g:loaded_gentags#ctags = !executable("ctags")
  let g:loaded_gentags#gtags = !executable("gtags")
  let g:gen_tags#ctags_auto_gen  = executable("ctags")
  let g:gen_tags#gtags_auto_gen  = executable("gtags")
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'ywatase/mdt.vim'
if = 'executable("mdt")'

