[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  if empty($SOLARIZED)
    let g:solarized_termtrans = 0
    let g:solarized_termcolors = 256
  else
    let g:solarized_termtrans = 1
    let g:solarized_termcolors = 16
  endif
  set background=dark
  autocmd MyAutoCmd VimEnter * nested colorscheme solarized
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/rc/lightline.rc.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'zchee/deoplete-zsh'

[[plugins]]
repo = 'zplug/vim-zplug'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_bufTypeExclude = ['nofile', 'help']
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
  nmap <Space>* <Plug>(quickhl-manual-this)
  nmap <Space>nohl <Plug>(quickhl-manual-reset)
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  " messages
  let g:ale_echo_msg_format = '[%linter%] %code: %%s [%severity%]'

  " linters
  let g:ale_linters = {
        \ 'go': ['go build', 'gofmt', 'golint',
        \        'gosimple', 'gotype', 'go vet', 'staticcheck'],
        \ }

  " fixers
  let g:ale_fix_on_save = 1
  let g:ale_go_gofmt_options = '-s'
  let g:ale_fixers = {
        \ 'go': ['gofmt', 'goimports'],
        \ }

  " Map movement through errors without wrapping.
  nmap <silent> <C-k> <Plug>(ale_previous)
  nmap <silent> <C-j> <Plug>(ale_next)
'''

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
if = 'executable("ctags") || executable("gtags")'
hook_add = '''
  let g:loaded_gentags#ctags = !executable("ctags")
  let g:loaded_gentags#gtags = !executable("gtags")
  let g:gen_tags#ctags_auto_gen  = executable("ctags")
  let g:gen_tags#gtags_auto_gen  = executable("gtags")
'''

[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = '''
  " prefix
  nnoremap [gtags] <NOP>
  nmap <Space>g [gtags]

  " keymap
  nnoremap <silent> [gtags]d :<C-u>DeniteCursorWord gtags_def -buffer-name=gtags -mode=normal<CR>
  nnoremap <silent> [gtags]r :<C-u>DeniteCursorWord gtags_ref -buffer-name=gtags -mode=normal<CR>
  nnoremap <silent> [gtags]c :<C-u>DeniteCursorWord gtags_context -buffer-name=gtags -mode=normal<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'ywatase/mdt.vim'
if = 'executable("mdt")'

