[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_cmd = 'Linediff'
hook_add = '''
  let g:linediff_first_buffer_command = 'topleft new'
  let g:linediff_second_buffer_command = 'vertical new'
  autocmd MyAutoCmd User LinediffBufferReady nnoremap <buffer> q :LinediffReset<cr>

  let g:linediff_modify_statusline = 0
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'TagbarToggle'
hook_add = '''
  let g:tagbar_autoshowtag = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_cmd = 'TableModeToggle'
hook_add = '''
  let g:table_mode_corner = '|'
'''
