[[plugins]]
repo = 'Shougo/denite.nvim'
rev = '67475c7'
frozen = 1
on_cmd = 'Denite'
hook_add = '''
  " prefix
  nnoremap <Plug>(denite) <NOP>
  nmap <Space>d <Plug>(denite)

  " keymap
  nnoremap <silent> <Plug>(denite)f :<C-u>Denite buffer `finddir('.git', ';') != '' ? 'file/rec/git' : 'file/rec'`<CR>
  nnoremap <silent> <Plug>(denite)if :<C-u>Denite file/rec/gitignore<CR>
  nnoremap <silent> <Plug>(denite)af :<C-u>Denite file/rec/all<CR>
  nnoremap <silent> <Plug>(denite)o :<C-u>Denite outline -auto-highlight -mode=normal<CR>
  nnoremap <silent> <Plug>(denite)/ :<C-u>Denite grep -no-empty -mode=normal<CR>
  nnoremap <silent> <Plug>(denite)* :<C-u>DeniteCursorWord grep -no-empty -mode=normal<CR>
  nnoremap <silent> <Plug>(denite)t :<C-u>Denite tag<CR>
  nnoremap <silent> <Plug>(denite)<C-]> :<C-u>DeniteCursorWord tag -mode=normal<CR>

  nnoremap <silent> <Plug>(denite)r :<C-u>Denite -resume<CR>
  nnoremap <silent> <Plug>(denite)n :<C-u>Denite -resume -cursor-pos=+1 -immediately<CR>
  nnoremap <silent> <Plug>(denite)p :<C-u>Denite -resume -cursor-pos=-1 -immediately<CR>

  nnoremap <silent> <Plug>(denite)b :<C-u>Denite buffer -buffer-name=buf<CR>
  nnoremap <silent> <Plug>(denite)h :<C-u>Denite help -buffer-name=help<CR>
  nnoremap <silent> <Plug>(denite): :<C-u>Denite command_history -buffer-name=history<CR>
  nnoremap <silent> <Plug>(denite)ein :<C-u>Denite dein_log -mode=normal<CR>

  nnoremap <silent> <Plug>(denite)cd :<C-u>DeniteProjectDir directory_rec -buffer-name=cd -default-action=cd<CR>

  "nnoremap <silent> <Space>/ :<C-u>Denite line -auto-highlight -auto-resize -buffer-name=line<CR>
  "nnoremap <silent> <Space>* :<C-u>DeniteCursorWord line -auto-highlight -auto-resize -buffer-name=line -mode=normal<CR>

  "nnoremap <silent> FT :<C-u>Denite filetype -buffer-name=ft<CR>
  "nnoremap <silent> <Plug>(denite)cs :<C-u>Denite colorscheme -buffer-name=cs<CR>

  nnoremap <silent> T :<C-u>Denite menu:toggle -buffer-name=toggle<CR>
'''
hook_source = 'source ~/.vim/rc/denite.rc.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = ['deoplete.nvim']
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
  imap <C-k>     <Plug>(neosnippet_jump_or_expand)
  smap <C-k>     <Plug>(neosnippet_jump_or_expand)
  xmap <C-k>     <Plug>(neosnippet_expand_target)

  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#expand_word_boundary = 1

  "let g:neosnippet#snippets_directory = 'path/to/snippets'
'''

# [[plugins]]
# repo = 'fatih/vim-go'
# on_ft = 'go'
# hook_source = '''
#   " for ALE
#   let g:go_fmt_autosave = 0
#
#   " highlight
#   let g:go_highlight_types = 1
#   let g:go_highlight_fields = 1
#   let g:go_highlight_functions = 1
#   let g:go_highlight_function_calls = 1
#   "let g:go_highlight_extra_types = 1
#   "let g:go_highlight_operators = 1
#   "let g:go_highlight_build_constraints = 1
#
#   let g:go_auto_sameids = 1
# '''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'TagbarToggle'
hook_add = '''
  let g:tagbar_autoshowtag = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_cmd = 'TableModeToggle'
hook_add = '''
  let g:table_mode_corner = '|'
'''
