[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_cmd = 'Linediff'
hook_add = '''
  let g:linediff_first_buffer_command = 'topleft new'
  let g:linediff_second_buffer_command = 'vertical new'
  autocmd MyAutoCmd User LinediffBufferReady nnoremap <buffer> q :LinediffReset<cr>

  let g:linediff_modify_statusline = 0
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'TagbarToggle'
hook_add = '''
  let g:tagbar_autoshowtag = 1
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
on_cmd = 'Vista'
hook_add = '''
  let g:vista_default_executive = 'vim_lsp'
  let g:vista_executive_for = {
              \ 'markdown': 'markdown',
              \ }
'''

[[plugins]]
repo = 'rbtnn/vim-emphasiscursor'
on_cmd = 'EmphasisCursor'
hook_add = '''
  nnoremap <Esc><Esc> <Cmd>EmphasisCursor<CR>
'''

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_event = 'CmdlineEnter'
hook_add = '''
  let g:loaded_sonictemplate_vim = 1
  command! -nargs=1 -complete=customlist,sonictemplate#complete Template call sonictemplate#apply(<f-args>, "n")
'''

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_cmd = 'TableModeToggle'
hook_add = '''
  let g:table_mode_corner = '|'
'''
